[build-system]

requires = ["setuptools>=68", "wheel"]

build-backend = "setuptools.build_meta"

 

[project]

name = "mi-lib-colab"

version = "0.1.0"

description = "Librería mínima para usar desde Google Colab"

requires-python = ">=3.9"

 

[tool.setuptools]

package-dir = {"" = "src"}

 
